### ISSUE TITLE
Version number increment

### ISSUE THREAD

**Issue by kartikayyer** [MathieuLeocmach/read_lif#5]
Hi guys, we have been using your very useful package and recently got burnt by the axis order change (1613c9bd81015e5f0fce8f03e2dbe5010bd37a6c). The change is actually good for us in terms of memory access. 

But since it breaks compatibility with the older version, I think there should be a big version number change, at least to 0.4, and maybe this could even be mentioned in the README.

**Comment by yangyushi** [comment]
Hi @kartikayyer, many thanks to your feedback! I did the two exact things you recommended. Now the version number is 0.4.0 and the compatibility issue is mentioned in the README.
